CREATE DATABASE APSystem;

USE APSystem;

CREATE TABLE [User]
(
	[Id] INT PRIMARY KEY IDENTITY,
	[Login] VARCHAR(100) NOT NULL,
	[Password] VARCHAR(255) NOT NULL,
	[CPF] VARCHAR(11) NOT NULL,
	[RG] VARCHAR(11) NOT NULL
)

CREATE TABLE [Passage]
(
	[Id] INT PRIMARY KEY IDENTITY,
	[IdUser] INT FOREIGN KEY REFERENCES [User](Id),
	[Type] VARCHAR(2) NOT NULL,
	[Number] VARCHAR(255) NOT NULL,
	[DepartureDate] DATETIME NOT NULL,
	[ArrivalDate] DATETIME NOT NULL
)